# Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Problem Statement

Given a dataset which represents the parameters of an Engineering gradute based on which that salary will be given to him/her. You have to build a model to predict the Engineering graduate salary based on the provided features.

# Importing the dataset

Link: https://drive.google.com/file/d/13fgjGI3uGlnEqefpZ72JsWLqXqveNKo1/view

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ShapeAI DST 11021 Oct-Jan Batch 2021-22/Datasets/Engineering_graduate_salary.csv')

# EDA - Exploratory Data Analysis

In [ ]:
df.head()

,ID,Gender,DOB,10percentage,10board,12graduation,12percentage,12board,CollegeID,CollegeTier,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
0,604399,f,1990-10-22,87.80,cbse,2009,84.00,cbse,6920,1,...,-1,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000
1,988334,m,1990-05-15,57.00,cbse,2010,64.50,cbse,6624,2,...,-1,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000
2,301647,m,1989-08-21,77.33,"maharashtra state board,pune",2007,85.17,amravati divisional board,9084,2,...,-1,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000
3,582313,m,1991-05-04,84.30,cbse,2009,86.00,cbse,8195,1,...,-1,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000
4,339001,f,1990-10-30,82.00,cbse,2008,75.00,cbse,4889,2,...,-1,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000

# Data Description
ID: A unique ID to identify a candidate

Salary: Annual CTC offered to the candidate (in INR)

Gender: Candidate's gender

DOB: Date of birth of the candidate

10percentage: Overall marks obtained in grade 10 examinations

10board: The school board whose curriculum the candidate followed in grade 10

12graduation: Year of graduation - senior year high school

12percentage: Overall marks obtained in grade 12 examinations

12board: The school board whose curriculum the candidate followed

CollegeID: Unique ID identifying the university/college which the candidate attended for her/his undergraduate

CollegeTier: Each college has been annotated as 1 or 2. The annotations have been computed from the average AMCAT scores obtained by the students in the college/university. Colleges with an average score above a threshold are tagged as 1 and others as 2.

Degree: Degree obtained/pursued by the candidate

Specialization: Specialization pursued by the candidate

CollegeGPA: Aggregate GPA at graduation

CollegeCityID: A unique ID to identify the city in which the college is located in.

CollegeCityTier: The tier of the city in which the college is located in. This is annotated based on the population of the cities.

CollegeState: Name of the state in which the college is located

GraduationYear: Year of graduation (Bachelor's degree)

English: Scores in AMCAT English section

Logical: Score in AMCAT Logical ability section

Quant: Score in AMCAT's Quantitative ability section

Domain: Scores in AMCAT's domain module

ComputerProgramming: Score in AMCAT's Computer programming section

ElectronicsAndSemicon: Score in AMCAT's Electronics & Semiconductor Engineering section

ComputerScience: Score in AMCAT's Computer Science section

MechanicalEngg: Score in AMCAT's Mechanical Engineering section

ElectricalEngg: Score in AMCAT's Electrical Engineering section

TelecomEngg: Score in AMCAT's Telecommunication Engineering section

CivilEngg: Score in AMCAT's Civil Engineering section

conscientiousness: Scores in one of the sections of AMCAT's personality test

agreeableness: Scores in one of the sections of AMCAT's personality test

extraversion: Scores in one of the sections of AMCAT's personality test

nueroticism: Scores in one of the sections of AMCAT's personality test

openesstoexperience: Scores in one of the sections of AMCAT's personality test

In [ ]:
df.tail()

,ID,Gender,DOB,10percentage,10board,12graduation,12percentage,12board,CollegeID,CollegeTier,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
2993,103174,f,1989-04-17,75.00,0,2005,73.00,0,1263,2,...,-1,-1,-1,-1,-1.1901,0.9688,-1.0697,1.35490,0.0284,120000
2994,352811,f,1991-07-22,84.00,state board,2008,77.00,state board,9481,2,...,-1,-1,-1,-1,-0.1082,0.0328,-0.4891,-0.29020,0.5024,120000
2995,287070,m,1988-11-24,91.40,bsemp,2006,65.56,bsemp,547,2,...,-1,-1,-1,-1,-0.8810,0.1888,-0.3440,0.06230,0.6603,385000
2996,317336,m,1988-08-25,88.64,karnataka education board,2006,65.16,karnataka education board,1629,2,...,-1,-1,-1,-1,1.4374,1.2808,-0.4891,-1.46537,0.5419,530000
2997,993701,m,1992-05-27,77.00,state board,2009,75.50,state board,1111,2,...,-1,-1,-1,-1,-0.5899,-1.9521,0.3174,1.16010,-2.3937,200000

In [ ]:
df.shape

(2998, 34)

In [ ]:
df.columns

Index(['ID', 'Gender', 'DOB', '10percentage', '10board', '12graduation',
       '12percentage', '12board', 'CollegeID', 'CollegeTier', 'Degree',
       'Specialization', 'collegeGPA', 'CollegeCityID', 'CollegeCityTier',
       'CollegeState', 'GraduationYear', 'English', 'Logical', 'Quant',
       'Domain', 'ComputerProgramming', 'ElectronicsAndSemicon',
       'ComputerScience', 'MechanicalEngg', 'ElectricalEngg', 'TelecomEngg',
       'CivilEngg', 'conscientiousness', 'agreeableness', 'extraversion',
       'nueroticism', 'openess_to_experience', 'Salary'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2998 entries, 0 to 2997
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID                     2998 non-null   int64
 1   Gender                 2998 non-null   object
 2   DOB                    2998 non-null   object
 3   10percentage           2998 non-null   float64
 4   10board                2998 non-null   object
 5   12graduation           2998 non-null   int64
 6   12percentage           2998 non-null   float64
 7   12board                2998 non-null   object
 8   CollegeID              2998 non-null   int64
 9   CollegeTier            2998 non-null   int64
 10  Degree                 2998 non-null   object
 11  Specialization         2998 non-null   object
 12  collegeGPA             2998 non-null   float64
 13  CollegeCityID          2998 non-null   int64
 14  CollegeCityTier        2998 non-null   int64
 15  CollegeState           2998 non-null   object
 16  GraduationYear         2998 non-null   int64
 17  English                2998 non-null   int64
 18  Logical                2998 non-null   int64
 19  Quant                  2998 non-null   int64
 20  Domain                 2998 non-null   float64
 21  ComputerProgramming    2998 non-null   int64
 22  ElectronicsAndSemicon  2998 non-null   int64
 23  ComputerScience        2998 non-null   int64
 24  MechanicalEngg         2998 non-null   int64
 25  ElectricalEngg         2998 non-null   int64
 26  TelecomEngg            2998 non-null   int64
 27  CivilEngg              2998 non-null   int64
 28  conscientiousness      2998 non-null   float64
 29  agreeableness          2998 non-null   float64
 30  extraversion           2998 non-null   float64
 31  nueroticism            2998 non-null   float64
 32  openess_to_experience  2998 non-null   float64
 33  Salary                 2998 non-null   int64
dtypes: float64(9), int64(18), object(7)
memory usage: 796.5+ KB

In [ ]:
df.isna().sum()

ID                       0
Gender                   0
DOB                      0
10percentage             0
10board                  0
12graduation             0
12percentage             0
12board                  0
CollegeID                0
CollegeTier              0
Degree                   0
Specialization           0
collegeGPA               0
CollegeCityID            0
CollegeCityTier          0
CollegeState             0
GraduationYear           0
English                  0
Logical                  0
Quant                    0
Domain                   0
ComputerProgramming      0
ElectronicsAndSemicon    0
ComputerScience          0
MechanicalEngg           0
ElectricalEngg           0
TelecomEngg              0
CivilEngg                0
conscientiousness        0
agreeableness            0
extraversion             0
nueroticism              0
openess_to_experience    0
Salary                   0
dtype: int64

In [ ]:
df.isna().sum().sum()

0

In [ ]:
df.columns

Index(['ID', 'Gender', 'DOB', '10percentage', '10board', '12graduation',
       '12percentage', '12board', 'CollegeID', 'CollegeTier', 'Degree',
       'Specialization', 'collegeGPA', 'CollegeCityID', 'CollegeCityTier',
       'CollegeState', 'GraduationYear', 'English', 'Logical', 'Quant',
       'Domain', 'ComputerProgramming', 'ElectronicsAndSemicon',
       'ComputerScience', 'MechanicalEngg', 'ElectricalEngg', 'TelecomEngg',
       'CivilEngg', 'conscientiousness', 'agreeableness', 'extraversion',
       'nueroticism', 'openess_to_experience', 'Salary'],
      dtype='object')

In [ ]:
# Removing the columns - ID, 10board, 12board, CollegeID, CollegeCityID, CollegeCityTier,
# CollegeCityTier, CollegeState

In [ ]:
df.drop(
    ['ID', '10board', '12board', 'CollegeID', 'CollegeCityID', 'CollegeCityTier',  'CollegeCityTier', 'CollegeState'],
    axis=1,
    inplace=True)

In [ ]:
# 34 -> (33 + 1) -> (25 + 1)

In [ ]:
df.head(1)

,Gender,DOB,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
0,f,1990-10-22,87.8,2009,84.0,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,...,-1,-1,-1,-1,-0.159,0.3789,1.2396,0.1459,0.2889,445000

In [ ]:
df.Gender.value_counts()

m    2282
f     716
Name: Gender, dtype: int64

In [ ]:
enc = LabelEncoder()

In [ ]:
df.Gender = enc.fit_transform(df.Gender)

In [ ]:
df.Gender.value_counts()

1    2282
0     716
Name: Gender, dtype: int64

m -> 1

f -> 0

In [ ]:
df.head(1)

,Gender,DOB,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
0,0,1990-10-22,87.8,2009,84.0,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,...,-1,-1,-1,-1,-0.159,0.3789,1.2396,0.1459,0.2889,445000

In [ ]:
df['10percentage'].describe()

count    2998.000000
mean       77.666264
std        10.002785
min        43.000000
25%        71.140000
50%        78.965000
75%        85.600000
max        97.760000
Name: 10percentage, dtype: float64

In [ ]:
df['12graduation'].describe()

count    2998.000000
mean     2008.080720
std         1.631814
min      1998.000000
25%      2007.000000
50%      2008.000000
75%      2009.000000
max      2012.000000
Name: 12graduation, dtype: float64

In [ ]:
df['12percentage'].describe()

count    2998.000000
mean       74.341061
std        11.120299
min        40.000000
25%        66.000000
50%        74.000000
75%        82.600000
max        98.700000
Name: 12percentage, dtype: float64

In [ ]:
# Age -> 2018 - x -> 2018 - 1990

In [ ]:
# GraduationYear

In [ ]:
df['GraduationYear'].describe()

count    2998.000000
mean     2011.939960
std        36.780582
min         0.000000
25%      2012.000000
50%      2013.000000
75%      2014.000000
max      2017.000000
Name: GraduationYear, dtype: float64

In [ ]:
newdf = df.copy()

In [ ]:
newdf['DOB'] = pd.to_datetime(newdf['DOB'])

In [ ]:
# 01-12-2015

In [ ]:
newdf.head(1)

,Gender,DOB,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
0,0,1990-10-22,87.8,2009,84.0,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,...,-1,-1,-1,-1,-0.159,0.3789,1.2396,0.1459,0.2889,445000

In [ ]:
newdf.DOB[0].year

1990

In [ ]:
newdf.DOB.max().year

1997

In [ ]:
newdf.DOB.min().year

1981

In [ ]:
df['DOB'] = pd.to_datetime(df['DOB'])

In [ ]:
df.head()

,Gender,DOB,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,...,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary
0,0,1990-10-22,87.80,2009,84.00,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,...,-1,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000
1,1,1990-05-15,57.00,2010,64.50,2,B.Tech/B.E.,computer science & engineering,65.00,2014,...,-1,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000
2,1,1989-08-21,77.33,2007,85.17,2,B.Tech/B.E.,electronics & telecommunications,61.94,2011,...,-1,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000
3,1,1991-05-04,84.30,2009,86.00,1,B.Tech/B.E.,computer science & engineering,80.40,2013,...,-1,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000
4,0,1990-10-30,82.00,2008,75.00,2,B.Tech/B.E.,biotechnology,64.30,2012,...,-1,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000

In [ ]:
for date in df['DOB']:
  print(2018 - date.year)

28
28
29
27
28
29
29
27
26
25
28
26
27
26
27
28
30
26
27
27
31
26
32
30
27
28
26
30
28
29
26
26
28
28
27
27
27
26
27
30
28
27
32
27
30
27
27
34
28
28
28
28
28
25
25
28
27
28
27
31
26
26
26
26
27
29
27
28
27
25
27
28
27
26
29
25
26
32
26
29
27
29
28
26
29
27
27
26
28
28
26
28
28
31
26
28
25
35
27
27
28
27
25
27
26
31
26
29
28
25
29
30
31
28
26
30
28
33
27
29
26
27
26
26
30
30
27
25
30
25
29
28
31
25
27
28
27
28
28
28
31
28
28
29
25
27
25
28
26
28
26
28
28
26
30
29
28
28
28
26
29
29
26
26
26
26
26
29
30
25
28
29
31
32
27
27
27
26
28
28
27
25
30
25
26
28
26
30
27
28
27
29
27
28
29
27
29
31
26
27
31
26
25
30
25
26
27
25
30
25
27
25
28
26
26
27
30
27
26
26
27
27
29
27
26
25
25
30
30
26
30
27
28
33
26
27
26
26
30
28
28
30
26
26
27
26
29
27
26
27
28
29
30
27
27
25
32
29
28
25
27
26
31
26
28
30
26
25
27
28
31
27
28
26
26
27
25
25
26
30
27
29
28
25
28
27
28
30
26
26
27
26
28
27
26
25
29
25
29
28
28
30
29
25
27
27
26
29
27
27
23
27
26
26
26
27
28
25
30
27
29
27
27
27
26
30
27
28
31
27
27
26
29
26
26
29
27
27
29
28
26
30
27
26
27
31
27
27
26
26
27
26
26
29
26
26
27
28
26
29
26
28
26
29
28
27
27
26
25
27
28
27
26
32
29
26
27
26
25
28
26
26
27
27
27
27
24
26
27
27
25
26
28
27
26
27
26
26
27
29
26
28
31
26
30
29
28
25
27
27
26
28
28
25
29
30
29
25
26
31
26
30
27
27
27
27
29
28
26
26
26
27
32
29
28
26
25
34
29
26
25
30
28
25
26
30
29
26
27
29
26
27
30
27
27
25
29
26
25
27
27
25
30
26
25
27
26
30
28
28
30
26
27
27
25
27
26
33
28
26
30
25
25
28
30
30
28
28
27
27
26
26
26
28
28
26
32
28
30
26
26
26
26
27
27
29
29
24
28
27
26
28
27
27
26
32
27
27
27
30
27
28
28
28
26
28
27
28
27
27
27
27
28
29
27
28
28
28
27
26
29
30
27
27
29
26
29
31
26
28
30
27
30
26
27
26
29
28
28
26
29
28
28
29
28
28
29
27
26
26
26
27
28
26
27
29
27
26
25
26
27
30
29
29
27
29
26
27
26
26
27
25
26
25
27
28
25
28
29
27
27
29
24
26
26
26
28
28
29
29
31
25
27
26
27
29
26
27
29
28
28
28
26
25
28
27
28
29
25
28
26
27
25
27
28
31
30
25
25
29
26
25
27
28
27
30
26
28
27
30
30
28
26
25
27
30
27
31
26
28
26
25
32
29
27
30
27
25
34
30
27
28
32
27
26
29
26
26
28
27
26
27
27
28
26
26
27
27
29
30
28
28
25
27
29
27
27
30
27
26
27
27
29
27
28
30
29
28
26
26
28
26
26
26
30
27
27
26
28
27
26
29
30
30
26
28
29
31
29
29
29
30
27
26
31
27
28
27
29
27
27
26
25
32
27
29
26
26
29
35
30
27
27
26
32
27
30
25
27
29
28
25
28
26
27
28
28
29
26
26
27
26
27
29
26
27
28
27
31
29
26
26
25
26
29
31
28
29
30
27
26
27
28
26
27
29
29
28
25
27
25
28
27
31
27
27
28
26
29
30
29
30
28
26
27
28
28
28
31
29
28
26
26
27
28
28
28
27
28
27
27
27
30
25
29
27
27
30
30
27
26
26
25
27
27
27
29
30
30
28
27
26
28
26
25
27
25
29
27
28
26
29
27
26
30
26
27
28
25
28
26
27
26
26
26
27
29
26
29
26
26
29
29
29
27
30
30
27
29
26
30
25
27
32
27
26
26
28
29
30
26
28
29
27
29
28
30
25
28
28
29
26
28
27
28
29
27
27
26
27
27
27
26
34
25
26
30
27
29
28
26
27
29
31
27
25
27
27
27
30
28
28
28
26
26
28
27
27
27
29
29
26
28
26
27
29
26
26
31
27
27
27
27
27
28
28
28
30
26
26
30
26
29
26
27
26
27
28
27
29
27
32
28
30
30
28
27
26
27
26
30
30
26
27
28
28
27
29
26
28
27
26
30
29
27
27
27
31
26
28
29
26
33
26
25
27
25
29
28
27
27
26
30
29
34
26
25
30
26
28
27
30
25
29
29
30
30
28
27
27
27
29
27
27
27
27
28
25
29
25
26
26
28
28
28
30
28
27
25
26
26
26
28
28
28
25
28
29
28
28
30
25
30
25
26
29
26
29
28
26
29
28
27
30
32
26
29
24
32
28
25
29
27
28
27
26
27
28
29
29
26
28
26
28
28
26
26
28
26
26
27
27
28
28
27
27
28
27
27
27
25
26
28
27
27
26
27
27
27
29
28
27
28
29
29
28
28
31
26
28
26
28
27
25
28
28
28
26
27
27
28
29
28
28
26
27
26
27
29
26
29
27
24
27
27
27
27
27
29
28
25
29
27
28
28
26
30
26
27
25
26
26
25
26
28
27
27
29
26
29
28
27
27
27
29
28
28
27
29
28
28
29
28
28
26
27
28
27
27
28
27
32
25
27
26
27
27
32
27
27
26
25
28
26
30
27
27
26
26
28
26
27
27
28
26
34
25
28
27
27
28
26
28
28
27
27
25
29
26
27
27
26
29
27
25
27
30
29
30
29
28
27
28
25
28
30
25
28
28
26
28
31
29
27
25
27
32
27
29
26
26
26
31
29
34
27
29
30
26
28
28
28
28
29
27
26
26
28
29
27
29
29
28
30
26
26
26
31
30
26
25
30
24
28
25
29
26
28
33
25
26
27
28
29
27
27
27
28
28
32
27
24
25
28
28
27
29
26
27
29
26
26
28
27
26
27
26
27
30
28
28
29
28
30
28
29
27
25
28
28
27
29
30
28
27
28
27
28
25
27
27
27
26
30
26
26
28
27
27
30
30
27
27
28
28
29
33
26
26
28
32
29
29
29
28
27
32
32
27
30
26
28
27
29
26
30
26
25
30
26
30
25
27
34
26
29
26
26
27
26
27
28
29
27
29
32
26
26
30
26
32
29
26
29
29
29
30
29
27
28
25
25
28
26
29
26
27
31
28
28
27
29
27
24
28
27
30
27
25
29
28
28
27
28
27
26
26
29
28
27
28
28
29
27
31
25
27
25
28
29
27
29
26
28
27
30
27
30
26
28
27
27
27
28
30
28
26
25
24
26
31
26
27
29
25
25
29
25
28
30
30
27
30
29
27
30
26
31
29
26
27
27
25
28
30
27
29
28
28
28
28
25
27
28
32
27
28
28
26
28
31
29
26
26
26
30
26
29
27
26
26
27
27
28
27
30
28
33
27
25
28
25
28
26
27
28
24
32
27
26
26
26
31
25
29
25
27
30
26
27
29
28
24
27
29
27
26
31
28
26
28
28
27
28
26
29
28
27
26
27
28
26
30
30
30
25
26
26
28
27
32
26
26
26
28
25
28
27
27
25
24
27
29
28
24
25
26
28
30
26
30
27
27
29
28
28
27
25
27
26
27
26
26
26
31
28
30
27
25
28
26
30
26
26
27
26
27
26
27
27
26
27
27
26
27
26
25
28
29
27
27
26
25
26
28
28
33
28
29
25
28
29
28
26
30
29
29
28
26
28
27
28
29
29
29
30
28
25
29
31
26
27
26
26
28
28
29
27
27
26
26
28
27
28
27
27
27
26
28
28
26
28
29
29
30
28
30
29
26
27
32
29
26
26
26
26
26
26
27
26
35
27
36
27
27
29
28
25
28
26
30
26
27
32
26
26
25
28
25
28
28
28
27
30
29
29
27
28
30
28
27
27
30
28
28
26
28
27
26
28
26
27
27
25
25
28
24
26
26
29
27
26
29
27
33
31
28
26
27
31
32
25
26
25
29
27
28
26
27
28
27
26
28
28
28
26
30
27
28
26
27
28
28
31
27
26
25
26
28
27
29
27
29
25
30
26
28
29
27
27
26
26
26
28
27
25
25
28
29
32
30
29
26
28
26
27
29
28
29
28
28
25
26
26
27
25
31
26
26
26
26
29
26
30
30
30
34
26
26
29
26
25
28
27
28
28
25
26
30
25
26
26
27
26
27
27
28
28
28
31
27
27
29
29
33
28
27
28
26
27
30
29
25
26
25
26
28
30
30
26
29
26
26
26
30
26
29
29
30
27
30
27
26
29
25
27
27
30
28
30
30
28
27
27
28
30
26
27
27
31
28
28
26
28
28
27
28
30
27
27
28
28
26
29
25
26
30
28
30
31
26
29
29
27
29
25
30
26
28
26
27
32
25
27
26
26
28
28
28
26
31
29
26
26
31
28
29
26
28
28
27
26
26
27
28
29
28
26
26
25
27
26
30
25
28
26
29
28
26
28
29
28
26
27
28
28
27
29
28
27
27
27
27
29
30
29
25
30
29
25
27
27
28
28
26
27
27
27
28
30
27
37
27
32
27
28
28
29
27
29
26
24
26
29
27
27
28
28
29
29
27
26
29
28
26
26
30
30
28
26
26
26
27
32
29
27
29
27
29
26
31
27
27
27
29
32
26
26
29
30
30
29
25
27
27
27
30
29
28
26
26
30
28
29
29
28
26
29
26
27
30
27
27
29
26
28
31
30
27
27
29
26
32
25
30
31
27
26
29
25
28
30
27
26
25
26
27
25
28
27
25
28
26
25
26
27
26
26
26
25
25
26
31
28
26
26
26
26
26
28
28
26
29
30
26
27
29
29
27
27
26
28
29
25
28
29
29
27
25
27
26
31
30
26
31
28
30
27
25
27
26
25
25
28
31
29
27
30
31
29
28
30
27
25
27
29
26
26
32
27
26
29
28
27
26
27
25
27
25
25
28
25
27
27
26
25
27
26
28
29
27
26
26
28
29
25
27
30
26
25
30
27
29
29
26
25
26
28
28
28
26
27
27
25
25
28
30
32
28
26
26
30
25
28
27
29
29
26
27
27
26
27
28
30
28
26
26
27
28
26
29
26
27
26
30
31
27
27
27
26
26
26
26
25
28
25
31
29
27
27
29
30
26
26
26
27
27
26
27
29
28
26
27
28
25
28
27
30
29
25
28
26
28
26
29
30
28
29
27
26
28
26
30
27
26
26
26
29
26
26
27
26
27
28
27
29
28
26
26
28
27
26
28
29
33
26
30
28
28
27
26
26
26
25
28
26
32
26
26
29
28
30
29
26
29
27
31
27
25
27
26
29
26
30
26
28
28
28
29
30
26
25
26
25
28
30
28
27
28
27
27
27
28
26
30
28
26
27
27
27
29
26
27
30
29
29
25
31
28
30
26
27
31
28
30
27
30
26
31
28
26
27
28
27
28
31
27
29
27
30
29
27
30
26
25
28
28
28
28
27
28
28
26
33
29
29
27
28
26
30
29
27
26
27
27
28
30
29
27
27
30
26
28
26
29
28
26
28
25
29
26
27
29
26
28
28
26
27
26
26
31
26
30
27
29
31
26
29
27
26
26
29
29
25
26
27
28
26
24
28
26
27
27
26
28
30
30
27
27
27
27
30
28
28
27
27
27
27
27
27
27
27
27
27
28
30
29
27
26
26
27
27
27
27
28
29
26
29
26
27
27
27
30
28
30
26
26
27
26
28
26
28
29
27
28
26
28
26
32
31
31
25
29
30
25
30
29
25
27
28
33
28
26
28
28
25
27
30
29
26
28
27
27
29
26
26
27
30
26
30
31
28
26
24
29
29
28
26
28
27
27
26
27
26
26
28
28
29
28
26
28
26
29
28
29
27
31
26
27
29
27
27
28
26
29
26
27
28
26
27
27
27
27
27
29
27
27
25
26
29
28
26
26
28
26
30
28
29
31
34
30
30
29
26
27
29
30
27
26
28
26
26
27
26
27
27
27
27
27
28
29
25
26
26
30
29
28
27
26
25
29
27
26
28
26
28
28
23
25
27
27
27
26
26
30
27
28
27
31
29
28
29
31
25
29
28
28
27
25
34
27
26
31
26
28
28
28
30
31
30
26
26
28
29
26
30
27
28
28
30
27
26
31
32
29
28
28
26
27
29
29
27
31
25
28
31
27
29
27
28
27
26
26
27
31
26
26
27
28
29
26
29
28
31
28
28
26
26
28
27
25
29
21
26
27
27
28
27
27
27
29
29
29
27
27
26
27
29
28
28
27
29
29
29
25
27
33
33
25
27
29
29
28
28
25
28
29
27
28
29
26
28
28
30
26
27
27
27
26
28
27
27
27
29
27
31
28
24
27
29
29
26
27
26
30
25
30
26
27
26
29
28
27
27
30
24
27
28
28
26
28
29
32
25
26
28
26
29
30
27
26
26
29
31
31
30
26
29
29
27
28
29
25
29
29
32
29
28
27
27
27
28
28
26
26
27
26
30
29
27
27
25
26
27
26
29
32
25
27
26
27
27
29
28
27
28
31
27
25
29
26
26
29
29
27
26
28
29
25
27
28
29
27
27
27
27
25
29
28
27
30
27
26
30
28
26
29
28
28
28
27
29
28
26
31
27
27
30
26
28
29
26
25
27
27
26
27
27
27
30
27
28
28
29
29
30
28
28
27
25
29
33
32
29
27
30
30
26

In [ ]:
age = []

In [ ]:
for date in df['DOB']:
  age.append(2018 - int(date.year))

df['Age'] = age

In [ ]:
df.head()

,Gender,DOB,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,...,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,Age
0,0,1990-10-22,87.80,2009,84.00,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,...,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000,28
1,1,1990-05-15,57.00,2010,64.50,2,B.Tech/B.E.,computer science & engineering,65.00,2014,...,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000,28
2,1,1989-08-21,77.33,2007,85.17,2,B.Tech/B.E.,electronics & telecommunications,61.94,2011,...,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000,29
3,1,1991-05-04,84.30,2009,86.00,1,B.Tech/B.E.,computer science & engineering,80.40,2013,...,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000,27
4,0,1990-10-30,82.00,2008,75.00,2,B.Tech/B.E.,biotechnology,64.30,2012,...,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000,28

In [ ]:
df.drop('DOB', axis=1, inplace=True)

In [ ]:
df.head()

,Gender,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,English,...,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,Age
0,0,87.80,2009,84.00,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,650,...,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000,28
1,1,57.00,2010,64.50,2,B.Tech/B.E.,computer science & engineering,65.00,2014,440,...,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000,28
2,1,77.33,2007,85.17,2,B.Tech/B.E.,electronics & telecommunications,61.94,2011,485,...,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000,29
3,1,84.30,2009,86.00,1,B.Tech/B.E.,computer science & engineering,80.40,2013,675,...,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000,27
4,0,82.00,2008,75.00,2,B.Tech/B.E.,biotechnology,64.30,2012,575,...,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000,28

In [ ]:
df.CollegeTier.unique()

array([1, 2])

In [ ]:
df.CollegeTier.value_counts()

2    2772
1     226
Name: CollegeTier, dtype: int64

In [ ]:
df.shape[0]

2998

In [ ]:
2772/2998

0.9246164109406271

In [ ]:
80% - Train
20% - Test

In [ ]:
df.GraduationYear.describe()

count    2998.000000
mean     2011.939960
std        36.780582
min         0.000000
25%      2012.000000
50%      2013.000000
75%      2014.000000
max      2017.000000
Name: GraduationYear, dtype: float64

In [ ]:
df.head()

,Gender,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,English,...,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,Age
0,0,87.80,2009,84.00,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,650,...,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000,28
1,1,57.00,2010,64.50,2,B.Tech/B.E.,computer science & engineering,65.00,2014,440,...,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000,28
2,1,77.33,2007,85.17,2,B.Tech/B.E.,electronics & telecommunications,61.94,2011,485,...,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000,29
3,1,84.30,2009,86.00,1,B.Tech/B.E.,computer science & engineering,80.40,2013,675,...,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000,27
4,0,82.00,2008,75.00,2,B.Tech/B.E.,biotechnology,64.30,2012,575,...,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000,28

In [ ]:
df.Degree.unique()

array(['B.Tech/B.E.', 'M.Tech./M.E.', 'MCA', 'M.Sc. (Tech.)'],
      dtype=object)

In [ ]:
df.Degree.value_counts()

B.Tech/B.E.      2757
MCA               200
M.Tech./M.E.       40
M.Sc. (Tech.)       1
Name: Degree, dtype: int64

In [ ]:
BTech/B.E. -> "Bachelors"
MCA, M.Tech./M.E., M.Sc. (Tech.) -> 'Masters'

In [ ]:
df.Specialization.value_counts()

electronics and communication engineering      670
computer science & engineering                 557
information technology                         506
computer engineering                           415
computer application                           201
mechanical engineering                         155
electronics and electrical engineering         148
electronics & telecommunications                89
electrical engineering                          63
electronics & instrumentation eng               24
instrumentation and control engineering         18
information science engineering                 18
electronics and instrumentation engineering     18
civil engineering                               15
electronics engineering                         13
biotechnology                                   12
other                                           10
industrial & production engineering              8
chemical engineering                             7
applied electronics and instrumentation          5
mechanical and automation                        5
telecommunication engineering                    4
automobile/automotive engineering                4
computer science and technology                  4
aeronautical engineering                         3
instrumentation engineering                      3
electronics and computer engineering             3
mechatronics                                     3
metallurgical engineering                        2
industrial engineering                           2
biomedical engineering                           2
information & communication technology           1
electronics                                      1
embedded systems technology                      1
industrial & management engineering              1
electrical and power engineering                 1
computer and communication engineering           1
mechanical & production engineering              1
control and instrumentation engineering          1
ceramic engineering                              1
computer networking                              1
information science                              1
Name: Specialization, dtype: int64

In [ ]:
df.head()

,Gender,10percentage,12graduation,12percentage,CollegeTier,Degree,Specialization,collegeGPA,GraduationYear,English,...,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience,Salary,Age
0,0,87.80,2009,84.00,1,B.Tech/B.E.,instrumentation and control engineering,73.82,2013,650,...,-1,-1,-1,-0.1590,0.3789,1.2396,0.14590,0.2889,445000,28
1,1,57.00,2010,64.50,2,B.Tech/B.E.,computer science & engineering,65.00,2014,440,...,-1,-1,-1,1.1336,0.0459,1.2396,0.52620,-0.2859,110000,28
2,1,77.33,2007,85.17,2,B.Tech/B.E.,electronics & telecommunications,61.94,2011,485,...,-1,260,-1,0.5100,-0.1232,1.5428,-0.29020,-0.2875,255000,29
3,1,84.30,2009,86.00,1,B.Tech/B.E.,computer science & engineering,80.40,2013,675,...,-1,-1,-1,-0.4463,0.2124,0.3174,0.27270,0.4805,420000,27
4,0,82.00,2008,75.00,2,B.Tech/B.E.,biotechnology,64.30,2012,575,...,-1,-1,-1,-1.4992,-0.7473,-1.0697,0.06223,0.1864,200000,28

In [ ]:
df.collegeGPA.describe()

count    2998.000000
mean       71.509857
std         8.122462
min         6.630000
25%        66.530000
50%        71.800000
75%        76.300000
max        99.930000
Name: collegeGPA, dtype: float64

In [ ]:
df.GraduationYear.describe()

count    2998.000000
mean     2011.939960
std        36.780582
min         0.000000
25%      2012.000000
50%      2013.000000
75%      2014.000000
max      2017.000000
Name: GraduationYear, dtype: float64

In [ ]:
df.columns

Index(['Gender', '10percentage', '12graduation', '12percentage', 'CollegeTier',
       'Degree', 'Specialization', 'collegeGPA', 'GraduationYear', 'English',
       'Logical', 'Quant', 'Domain', 'ComputerProgramming',
       'ElectronicsAndSemicon', 'ComputerScience', 'MechanicalEngg',
       'ElectricalEngg', 'TelecomEngg', 'CivilEngg', 'conscientiousness',
       'agreeableness', 'extraversion', 'nueroticism', 'openess_to_experience',
       'Salary', 'Age'],
      dtype='object')

In [ ]:
df.English.describe()

count    2998.000000
mean      501.066378
std       105.304512
min       180.000000
25%       425.000000
50%       500.000000
75%       570.000000
max       875.000000
Name: English, dtype: float64

In [ ]:
df.Logical.describe()

count    2998.000000
mean      500.431621
std        87.299850
min       195.000000
25%       441.250000
50%       505.000000
75%       565.000000
max       795.000000
Name: Logical, dtype: float64

In [ ]:
df.Quant.describe()

count    2998.000000
mean      514.137759
std       122.194955
min       120.000000
25%       430.000000
50%       515.000000
75%       595.000000
max       900.000000
Name: Quant, dtype: float64

In [ ]:
df.Domain.describe()

count    2998.000000
mean        0.508458
std         0.463373
min        -1.000000
25%         0.342315
50%         0.622643
75%         0.835612
max         0.999910
Name: Domain, dtype: float64

In [ ]:
-1 to 1

In [ ]:
df.columns

Index(['Gender', '10percentage', '12graduation', '12percentage', 'CollegeTier',
       'Degree', 'Specialization', 'collegeGPA', 'GraduationYear', 'English',
       'Logical', 'Quant', 'Domain', 'ComputerProgramming',
       'ElectronicsAndSemicon', 'ComputerScience', 'MechanicalEngg',
       'ElectricalEngg', 'TelecomEngg', 'CivilEngg', 'conscientiousness',
       'agreeableness', 'extraversion', 'nueroticism', 'openess_to_experience',
       'Salary', 'Age'],
      dtype='object')

In [ ]:
'ComputerProgramming', 'ElectronicsAndSemicon', 'ComputerScience', 'MechanicalEngg',
       'ElectricalEngg', 'TelecomEngg', 'CivilEngg'

In [ ]:
CS    E CP ME EL TE C
900 -1 -1 -1 -1 -1 -1
-1. 900 900 -1 -1 -1 -1

In [ ]:
DOMAIN
900
900

In [ ]:
df['Domain']

In [ ]:
model = SVR()

In [ ]:
X = df.drop('Salary')
y = df.Salary

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
model.fit(X_train, y_train)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

In [ ]:
model.predict([[_,_,_,......,_]])